name:  deploy

on:
      workflow_call:
      
jobs:

      build:
            runs-on: ubuntu-latest
            steps:
                  -name :
                  run: echo "code deployed using k8s"
